# Generated by Django 2.0.7 on 2018-07-28 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_blog_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='author',
            new_name='name',
        ),
    ]
