# Generated by Django 2.0.7 on 2018-08-03 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180731_0255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='name',
            new_name='author',
        ),
    ]
