# Generated by Django 2.0.7 on 2018-08-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180803_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='genre',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
