# Generated by Django 2.0.7 on 2018-08-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20180806_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
