# Generated by Django 2.0.7 on 2018-08-05 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_blog_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='picture',
        ),
    ]
